name: django
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install django
      - name: Migrate
        run: |
          python manage.py migrate --noinput
      - name: Tests
        run: |
          python manage.py test -v 2
