services:
  db:
    image: postgres:16
    env_file: .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - medj21_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./secrets:/app/secrets:ro
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  ocrapi:
    build:
      context: ./ocrapi
      dockerfile: Dockerfile
    env_file: .env.dev
    volumes:
      - ./secrets:/app/secrets:ro
    ports:
      - "5000:5000"

  tailwind:
    build:
      context: .
      dockerfile: ./theme/Dockerfile
    volumes:
      - .:/app

volumes:
  medj21_db_data: