services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  ocr:
    build:
      context: ./ocrapi
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.ocr
    ports:
      - "5000:5000"
    volumes:
      - ./ocrapi:/app/ocrapi

volumes:
  pgdata_dev:
