from django.urls import path
from . import views

urlpatterns = [
    path("", views.landing_page, name="landingpage"),
    path("login/", views.custom_login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),

    path("dashboard/", views.dashboard, name="dashboard"),
    path("casefiles/", views.casefiles, name="casefiles"),
    path("personal-card/", views.personal_card, name="personal_card"),
    path("upload/", views.upload_page, name="upload"),
    path("uploads/", views.upload_history, name="upload_history"),
    path("documents/", views.documents, name="documents"),
    path("documents/<int:pk>/", views.document_detail, name="document_detail"),
    path("documents/<int:pk>/edit/", views.document_edit, name="document_edit"),
    path("documents/<int:pk>/tags/", views.document_edit_tags, name="document_edit_tags"),
    path("documents/<int:pk>/move/", views.document_move, name="document_move"),
    path("documents/<int:pk>/pdf/", views.generate_pdf, name="document_pdf"),
    path("events/", views.event_list, name="events_list"),
    path("events/<int:pk>/", views.event_detail, name="event_detail"),
    path("events/<int:pk>/history/", views.event_history, name="event_history"),
    path("events/<int:pk>/update/", views.update_event_details, name="update_event_details"),
    path("labtests/", views.labtests, name="lab-tests"),
    path("labtests/<int:event_id>/", views.labtests_view, name="lab-tests_view"),
    path("labtests/<int:event_id>/edit/", views.labtest_edit, name="labtest_edit"),
    path("share/", views.share_document_page, name="share_document_page"),
    path("share/create/", views.create_share_token, name="create_share_token"),
    path("share/<str:token>/", views.share_view, name="share_view"),
    path("share/<str:token>/qr/", views.share_qr, name="share_qr"),
    path("share/<str:token>/revoke/", views.share_revoke, name="share_revoke"),
    path("ajax/events-by-specialty/", views.events_by_specialty, name="events_by_specialty"),
    path("ajax/tags-autocomplete/", views.tags_autocomplete, name="tags_autocomplete"),
    path("ajax/documents/<int:document_id>/delete/", views.delete_document, name="delete_document"),
    path("ajax/documents/add-medication-tag/", views.add_medication_tag, name="add_medication_tag"),
    path("files/<uuid:file_uuid>/", views.serve_file_by_uuid, name="serve_file_by_uuid"),
    path("export/event/<int:pk>/pdf/", views.export_event_pdf, name="export_event_pdf"),
    path("export/labs.csv", views.export_lab_csv, name="export_lab_csv"),
    path("health/", views.healthcheck, name="healthcheck"),
]