# Generated by Django 5.2.6 on 2025-09-18 19:23

from django.conf import settings
from django.db import migrations, models


def copy_sha_to_content(apps, schema_editor):
    Document = apps.get_model("records", "Document")
    for doc in Document.objects.exclude(sha256__isnull=True).exclude(sha256=""):
        if not doc.content_hash:
            doc.content_hash = doc.sha256
            doc.save(update_fields=["content_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(copy_sha_to_content, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("owner", "content_hash"),
                name="document_owner_content_hash_unique",
            ),
        ),
    ]
