# Generated by Django 5.2.6 on 2025-09-18 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_document_content_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="document_owner_content_hash_unique",
        ),
        migrations.AlterField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_hash__isnull", False)),
                fields=("owner", "content_hash"),
                name="document_owner_content_hash_unique",
            ),
        ),
    ]
