# Generated by Django 5.2.6 on 2025-09-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_remove_document_document_owner_content_hash_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="analysis_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="analysis_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
