version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medj
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medj -d medj"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  ocrapi:
    build:
      context: ../..
      dockerfile: docker/ocrapi/Dockerfile
    environment:
      FLASK_APP: ocrapi.app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: "5000"
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/ocr-key-vision.json
      OCR_FALLBACK: "tesseract"
    volumes:
      - ./:/app
      - ./secrets:/secrets:ro
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      DATABASE_URL: postgres://medj:medj@db:5432/medj
      OCRAPI_URL: http://ocrapi:5000
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
      ocrapi:
        condition: service_healthy
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
