# docker/compose/docker-compose.dev.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medj
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U medj -d medj"]
      interval: 10s
      timeout: 5s
      retries: 10

  ocr:
    build:
      context: ../..
      dockerfile: docker/ocrapi/Dockerfile
    ports:
      - "5000:5000"

  web:
    build:
      context: ../..
      dockerfile: docker/web/Dockerfile
    environment:
      DJANGO_ENVIRONMENT: dev
      OCR_SERVICE_URL: http://ocr:5000
      OPENAI_API_KEY: secrets/oprnai-key.txt
    depends_on:
      db:
        condition: service_healthy
      ocr:
        condition: service_started
    volumes:
      - ../..:/app
    ports:
      - "8000:8000"

volumes:
  pgdata:
