services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medjpass
    volumes:
      - medj_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ocrapi:
    build:
      context: ../../ocrapi
    image: compose-ocrapi
    env_file:
      - ../env/ocr.dev.env
    volumes:
      - ../../:/app
      - ../../secrets:/app/secrets:ro
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    build:
      context: ../..
      dockerfile: docker/web/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: medj.settings.dev
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medjpass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      OCR_API_URL: http://ocrapi:5000/ocr
      RUN_INITIAL_SEED: "${RUN_INITIAL_SEED:-}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME:-}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL:-}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD:-}"
    volumes:
      - ../../:/app
      - ../../secrets:/app/secrets:ro
    depends_on:
      - db
      - ocrapi
    ports:
      - "8000:8000"

volumes:
  medj_pg_data:
