services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medj}
      POSTGRES_USER: ${POSTGRES_USER:-medj}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-medjpass}
    volumes:
      - medj_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ocrapi:
    build:
      context: ../..
      dockerfile: docker/ocrapi/Dockerfile
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      FLASK_RUN_PORT: "5000"
      FLASK_APP: app:app
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/ocr-key-vision.json
    volumes:
      - ../../:/app
      - ../../secrets:/app/secrets:ro
    ports:
      - "5000:5000"

  web:
    build:
      context: ../..
      dockerfile: docker/web/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: medj.settings
      DB_HOST: db
      DB_PORT: "5432"
      OCR_API_URL: http://ocrapi:5000/ocr
      RUN_INITIAL_SEED: "${RUN_INITIAL_SEED:-}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME:-}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL:-}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD:-}"
    volumes:
      - ../../:/app
      - ../../secrets:/app/secrets:ro
    depends_on:
      - db
      - ocrapi
    ports:
      - "8000:8000"

volumes:
  medj_pg_data:
