services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medjpass
    volumes:
      - medj_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ocrapi:
    build:
      context: ../..
      dockerfile: docker/ocrapi/Dockerfile
    image: ocrapi
    entrypoint: /usr/local/bin/ocrapi-entrypoint
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: "5000"
      FLASK_APP: app:app
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/gcloudvision-service-key.json
    volumes:
      - ../../:/app
      - ../../secrets:/app/secrets:ro
    ports: ["5000:5000"]

  web:
    build:
      context: ../..
      dockerfile: docker/web/Dockerfile
    image: compose-web
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      DJANGO_SETTINGS_MODULE: medj.settings.dev
      DEBUG: "1"
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medjpass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      OCR_API_URL: http://ocrapi:5000/ocr
      DJANGO_SECRET_KEY_FILE: /app/secrets/django-key.txt
      OPENAI_API_KEY_FILE: /app/secrets/openai-key.txt
      RUN_INITIAL_SEED: "1"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "adminpass"
    depends_on:
      - db
      - ocrapi
    volumes:
      - ../../:/app
      - ../../secrets:/app/secrets:ro
    ports:
      - "8000:8000"

volumes:
  medj_pg_data:
