services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medj}
      POSTGRES_USER: ${POSTGRES_USER:-medj}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-medjpass}
    volumes:
      - medj_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ocrapi:
    build:
      context: ../..
      dockerfile: docker/ocrapi/Dockerfile
    working_dir: /app/ocrapi
    env_file:
      - ../env/ocr.dev.env
    environment:
      PORT: ${PORT:-5000}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/secrets/ocr-key-vision.json}
    entrypoint: ["sh","-lc","/app/docker/ocrapi/entrypoint.dev.sh"]
    volumes:
      - ../../:/app
      - ../../secrets:/secrets:ro
    ports:
      - "5000:5000"

  web:
    build:
      context: ../..
      dockerfile: docker/web/Dockerfile
    working_dir: /app
    env_file:
      - ../env/web.dev.env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-/app/secrets/django-key.txt}
      OPENAI_API_KEY_FILE: ${OPENAI_API_KEY_FILE:-/app/secrets/openai-key.txt}
      OCR_API_URL: ${OCR_API_URL:-http://ocrapi:5000/ocr}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
    entrypoint: ["sh","-lc","/app/docker/web/entrypoint.dev.sh"]
    volumes:
      - ../../:/app
      - ../../secrets:/app/secrets:ro
    depends_on:
      - db
      - ocrapi
    ports:
      - "8000:8000"

volumes:
  medj_pg_data: