services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medj
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U medj -d medj -c 'select 1' >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  ocrapi:
    build:
      context: .
      dockerfile: docker/ocrapi/Dockerfile
    environment:
      FLASK_APP: ocrapi/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: "5000"
    command: python -m flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: medj.settings.dev
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: medj
      POSTGRES_USER: medj
      POSTGRES_PASSWORD: medj
      OCRAPI_BASE_URL: http://ocrapi:5000
      TAILWIND_WATCH_POLL: "500"
    depends_on:
      db:
        condition: service_healthy
      ocrapi:
        condition: service_started
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
